/*
 * TRANSLATION FILE (ENGLIGH)
 * 
 * Alternative to stringtable.csv which is simpler to install for the mission maker.
 * The token ""%1"" represents a dynamic value generated by the scripts, like a vehicle name.
 * 
 * Alternative au stringtable.csv qui est plus simple à installer pour le créateur de mission.
 * Le mot-clé ""%1"" représente une valeur dynamique fournie par les scripts, comme par exemple un nom de véhicule.
 */

STR_R3F_LOG_action_heliporter = "Подцепить груз";
STR_R3F_LOG_action_heliporter_fait = "Груз ""%1"" прицеплен.";
STR_R3F_LOG_action_heliport_larguer = "Отцепить груз";
STR_R3F_LOG_action_heliport_larguer_fait = "Груз ""%1"" отцеплен.";

STR_R3F_LOG_action_deplacer_objet = "Взять ""%1""";
STR_R3F_LOG_action_relacher_objet = "Поставить ""%1""";
//STR_R3F_LOG_action_aligner_pente = "Adjust to the slope";
//STR_R3F_LOG_action_aligner_sol = "Adjust to the ground";
//STR_R3F_LOG_action_aligner_horizon = "Adjust horizontally";
STR_R3F_LOG_action_tourner = "Повернуть влево\вправо (X / C кнопки)";
STR_R3F_LOG_action_rapprocher = "Приблизить/Удалить (F / R кнопки)";
STR_R3F_LOG_ne_pas_monter_dans_vehicule = "You can't get in a vehicle while you're carrying this object !";

STR_R3F_LOG_action_charger_deplace = "Загрузка объекта";
STR_R3F_LOG_action_selectionner_objet_charge = "Загрузить ""%1"" в...";
STR_R3F_LOG_action_charger_selection = "... загрузить в ""%1""";
STR_R3F_LOG_action_selectionner_objet_fait = "Выбрать назначение для ""%1""...";
STR_R3F_LOG_action_charger_en_cours = "Загрузка в процессе...";
STR_R3F_LOG_action_charger_fait = "The object ""%1"" загружен в... ""%2"".";
STR_R3F_LOG_action_charger_pas_assez_de_place = "Тут нет больше свободного места !";

STR_R3F_LOG_action_selectionner_objet_remorque = "Прицепить ""%1"" к...";
STR_R3F_LOG_action_remorquer_selection = "... прицепить к ""%1""";

STR_R3F_LOG_action_remorquer_deplace = "Объект на сцепке";
STR_R3F_LOG_action_detacher = "Отцепить объект";
STR_R3F_LOG_action_detacher_fait = "Объект отцеплен.";
STR_R3F_LOG_action_detacher_impossible_pour_ce_vehicule = "Только пилот может отцепить это.";

STR_R3F_LOG_action_contenu_vehicule = "Багажное отделение";
STR_R3F_LOG_action_decharger_en_cours = "Разгрузка в процессе...";
STR_R3F_LOG_action_decharger_fait = "Объект ""%1"" выгружен из машины.";
STR_R3F_LOG_action_decharger_deja_fait = "Для тупых! Уже выгружен !";
STR_R3F_LOG_action_decharger_deplacable_exceptionnel = "Warning : once released, this object will no more be movable manually.";

STR_R3F_LOG_action_ouvrir_usine = "Open the creation factory";
STR_R3F_LOG_action_creer_en_cours = "Creation in progress...";
STR_R3F_LOG_action_creer_fait = "The object ""%1"" has been created.";
STR_R3F_LOG_action_creer_pas_assez_credits = "The factory has not enough credits to create this object.";

STR_R3F_LOG_mutex_action_en_cours = "The current operation isn't finished !";
STR_R3F_LOG_joueur_dans_objet = "There is a player in the object ""%1"" !";
STR_R3F_LOG_objet_en_cours_transport = "The object ""%1"" is already in transit !";
STR_R3F_LOG_objet_remorque_en_cours = "Impossible because the object ""%1"" is towing another object !";
STR_R3F_LOG_trop_loin = "Impossible because the object ""%1"" is too far !";

STR_R3F_LOG_dlg_CV_titre = "Багажник";
STR_R3F_LOG_dlg_CV_capacite_vehicule = "Загружено:  %1 / %2";
STR_R3F_LOG_dlg_CV_btn_decharger = "Выгрузить";
STR_R3F_LOG_dlg_CV_btn_fermer = "Отмена";

STR_R3F_LOG_dlg_LO_titre = "Creation factory";
STR_R3F_LOG_dlg_LO_credits_restants = "Remaining credits : %1";
STR_R3F_LOG_dlg_LO_btn_creer = "Создать";
STR_R3F_LOG_dlg_LO_btn_fermer = "Отмена";

STR_R3F_LOG_nom_fonctionnalite_proprietes = "Properties";
STR_R3F_LOG_nom_fonctionnalite_side = "Side";
STR_R3F_LOG_nom_fonctionnalite_places = "Seating";
STR_R3F_LOG_nom_fonctionnalite_passif = "It can be :";
STR_R3F_LOG_nom_fonctionnalite_passif_deplace = "Moved by player";
STR_R3F_LOG_nom_fonctionnalite_passif_heliporte = "Lifted";
STR_R3F_LOG_nom_fonctionnalite_passif_remorque = "Towed";
STR_R3F_LOG_nom_fonctionnalite_passif_transporte = "Transported";
STR_R3F_LOG_nom_fonctionnalite_passif_transporte_capacite = "load cost %1";
STR_R3F_LOG_nom_fonctionnalite_actif = "It can :";
STR_R3F_LOG_nom_fonctionnalite_actif_heliporte = "Lift";
STR_R3F_LOG_nom_fonctionnalite_actif_remorque = "Tow";
STR_R3F_LOG_nom_fonctionnalite_actif_transporte = "Transport";
STR_R3F_LOG_nom_fonctionnalite_actif_transporte_capacite = "max load %1";